/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppEditorRenderer: typeof import('./src/components/AppEditorRenderer/AppEditorRenderer.vue')['default']
    AppLeftPanel: typeof import('./src/components/AppLeftPanel/AppLeftPanel.vue')['default']
    AppNavigator: typeof import('./src/components/AppNavigator.vue')['default']
    AppRightPanel: typeof import('./src/components/AppRightPanel/AppRightPanel.vue')['default']
    AppRunnerRenderer: typeof import('./src/components/AppRunnerRenderer/AppRunnerRenderer.vue')['default']
    BlocksDrawer: typeof import('./src/components/AppLeftPanel/BlocksDrawer.vue')['default']
    CanvasChartRenderer: typeof import('./src/components/ChartRenderer/CanvasChartRenderer/CanvasChartRenderer.vue')['default']
    ChartRenderer: typeof import('./src/components/ChartRenderer/ChartRenderer.vue')['default']
    DataSourceContent: typeof import('./src/components/DataSourceContent/DataSourceContent.vue')['default']
    DataSourceLeftPanel: typeof import('./src/components/DataSourceLeftPanel.vue')['default']
    EchartsRenderer: typeof import('./src/components/ChartRenderer/EchartsRenderer/EchartsRenderer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    FlowEditor: typeof import('./src/components/FlowEditor/FlowEditor.vue')['default']
    LaptopPreviewer: typeof import('./src/components/AppEditorRenderer/LaptopPreviewer.vue')['default']
    MobilePreviewer: typeof import('./src/components/AppEditorRenderer/MobilePreviewer.vue')['default']
    NotesEditor: typeof import('./src/components/NotesEditor/NotesEditor.vue')['default']
    OutlineDrawer: typeof import('./src/components/AppLeftPanel/OutlineDrawer.vue')['default']
    PreviewModeSwitcher: typeof import('./src/components/AppEditorRenderer/PreviewModeSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaExporter: typeof import('./src/components/AppRightPanel/SchemaExporter.vue')['default']
    SegmentedControl: typeof import('./src/components/SegmentedControl/SegmentedControl.vue')['default']
    StatusBar: typeof import('./src/components/AppEditorRenderer/StatusBar.vue')['default']
    SVGChartRenderer: typeof import('./src/components/ChartRenderer/SVGChartRenderer/SVGChartRenderer.vue')['default']
  }
}
