version: '3'
services:
  build-less-code-show:
    build:
      context: .
      dockerfile: build.Dockerfile
    ports:
      - 4000:80
    restart: always
  dist-less-code-show:
    build:
      context: .
      dockerfile: dist.Dockerfile
    ports:
      - 5000:80
    restart: always
